Youshu:
  data_path: '../data/warm'
  batch_size_train: 2048
  batch_size_test: 2048
  topk: [10, 20, 40, 80]
  topk_valid: 20

  embedding_size: 64
  num_layers: 1

  aff_ed_ratio: 0.3
  hist_ed_ratio: 0.3
  agg_ed_ratio: 0.3

  residual_coff: 0.6

  lr: 2.0e-3
  lambda2: 1.0e-4
  lambda1: 0.1

  max_temp: 10000

  epochs: 100
  test_interval: 5

  aug_type: 'MD'

NetEase:
  data_path: '../data/all'
  batch_size_train: 4096
  batch_size_test: 2048
  topk: [10, 20, 40, 80]
  topk_valid: 20

  embedding_size: 64
  num_layers: 1

  aff_ed_ratio: 0.1
  hist_ed_ratio: 0.3
  agg_ed_ratio: 0.1

  residual_coff: 0.3

  lr: 1.0e-3
  lambda2: 1.0e-4
  lambda1: 0.1

  max_temp: 10000

  epochs: 100
  test_interval: 5

  aug_type: 'Noise'

iFashion:
  data_path: '../data/cold'
  batch_size_train: 4096
  batch_size_test: 2048
  topk: [10, 20, 40, 80]
  topk_valid: 20

  embedding_size: 64
  num_layers: 1

  aff_ed_ratio: 0.2
  hist_ed_ratio: 0.2
  agg_ed_ratio: 0

  residual_coff: 0.6
  
  lr: 1.0e-3
  lambda2: 4.0e-5
  lambda1: 0.5

  max_temp: 10000

  epochs: 100
  test_interval: 5

  aug_type: 'MD'

Steam:
  data_path: '../data/warm'
  batch_size_train: 2048
  batch_size_test: 2048
  topk: [1, 3, 5, 10]
  topk_valid: 3


  embedding_size: 64
  num_layers: 1

  aff_ed_ratio: 0.1
  hist_ed_ratio: 0.1
  agg_ed_ratio: 0.1

  residual_coff: 0.2

  lr: 1.0e-2
  lambda2: 1.0e-4
  lambda1: 0.2

  max_temp: 10000

  epochs: 100
  test_interval: 5

  aug_type: 'MD'

clothing:
  data_path: '../data/cold'
  batch_size_train: 512
  batch_size_test: 512
  topk: [1, 3, 5, 10]
  topk_valid: 5


  embedding_size: 64
  num_layers: 1

  aff_ed_ratio: 0.1
  hist_ed_ratio: 0.1
  agg_ed_ratio: 0.1

  residual_coff: 0.2

  lr: 1.0e-2
  lambda2: 1.0e-4
  lambda1: 0.1

  max_temp: 10000

  epochs: 100
  test_interval: 5

  aug_type: 'MD'

electronic:
  data_path: '../data/cold'
  batch_size_train: 512
  batch_size_test: 512
  topk: [1, 3, 5, 10]
  topk_valid: 5


  embedding_size: 64
  num_layers: 1

  aff_ed_ratio: 0.1
  hist_ed_ratio: 0.1
  agg_ed_ratio: 0.1

  residual_coff: 0.2

  lr: 1.0e-2
  lambda2: 1.0e-4
  lambda1: 0.2

  max_temp: 10000

  epochs: 100
  test_interval: 5

  aug_type: 'MD'

food:
  data_path: '../data/cold'
  batch_size_train: 512
  batch_size_test: 512
  topk: [1, 3, 5, 10]
  topk_valid: 5


  embedding_size: 64
  num_layers: 1

  aff_ed_ratio: 0.1
  hist_ed_ratio: 0.1
  agg_ed_ratio: 0.1

  residual_coff: 0.2

  lr: 1.0e-2
  lambda2: 1.0e-4
  lambda1: 0.2

  max_temp: 10000

  epochs: 100
  test_interval: 5

  aug_type: 'MD'